import type { FunctionalComponent } from 'vue'
import {
  Activity,
  BarChart3,
  Bot,
  Brain,
  Cable,
  CalendarDays,
  ChartPie,
  CircleAlert,
  CircleHelp,
  ClipboardList,
  Cog,
  Cpu,
  Database,
  FileText,
  HeartPulse,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link2,
  List,
  Map,
  MapPin,
  Microscope,
  Network,
  PanelsTopLeft,
  Plug,
  Puzzle,
  ScrollText,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  TrainFront,
  TrendingUp,
  Upload,
  Users,
  Workflow,
  Wrench,
} from 'lucide-vue-next'

/** Keys referenced from `shared/rbac.json` `navigationGroups[].items[].navIcon`. */
export const NAV_MANIFEST_ICON_KEYS = [
  'executive',
  'parkLive',
  'queueCrowd',
  'rideOperations',
  'sparkplugLive',
  'otMetrics',
  'assetHealth',
  'aiForecasts',
  'aiModels',
  'unsExplorer',
  'mqttTopics',
  'adapterMarketplace',
  'registry',
  'masterData',
  'assetList',
  'parkExplorer',
  'assetMap',
  'visitorFlow',
  'templates',
  'importExport',
  'dataQuality',
  'liveOps',
  'incidents',
  'agentInbox',
  'agentRuns',
  'staffAllocation',
  'liveQueue',
  'hotelGuests',
  'addonBoard',
  'oee',
  'shiftHandover',
  'predictiveMaintenance',
  'sqdcClassic',
  'sqdcHierarchy',
  'aiInsights',
  'aiStudio',
  'itOtHub',
  'auditLog',
  'userManagement',
  'platformSettings',
  'help',
  'settings',
  'mqttSparkplug',
  'unsMqtt',
  'liveConnectivity',
  'simulatorLab',
  'adapterDevices',
  'adapterPipelineLog',
  'integrationsHub',
  'mlFeatureMonitor',
] as const

export type NavManifestIconKey = (typeof NAV_MANIFEST_ICON_KEYS)[number]

const map = {
  executive: BarChart3,
  parkLive: LayoutDashboard,
  queueCrowd: TrendingUp,
  rideOperations: TrainFront,
  sparkplugLive: Cable,
  otMetrics: ChartPie,
  assetHealth: HeartPulse,
  aiForecasts: Activity,
  aiModels: Brain,
  unsExplorer: Network,
  mqttTopics: List,
  adapterMarketplace: Store,
  registry: Database,
  masterData: Database,
  assetList: List,
  parkExplorer: Map,
  assetMap: MapPin,
  visitorFlow: Users,
  templates: FileText,
  importExport: Upload,
  dataQuality: ShieldCheck,
  liveOps: LayoutDashboard,
  incidents: CircleAlert,
  agentInbox: Inbox,
  agentRuns: Bot,
  staffAllocation: Users,
  liveQueue: Activity,
  hotelGuests: CalendarDays,
  addonBoard: Puzzle,
  oee: ChartPie,
  shiftHandover: ClipboardList,
  predictiveMaintenance: Wrench,
  sqdcClassic: LayoutGrid,
  sqdcHierarchy: PanelsTopLeft,
  aiInsights: Lightbulb,
  aiStudio: Sparkles,
  itOtHub: Network,
  auditLog: ScrollText,
  userManagement: Users,
  platformSettings: Cog,
  help: CircleHelp,
  settings: Settings,
  mqttSparkplug: Cable,
  unsMqtt: Network,
  liveConnectivity: Activity,
  simulatorLab: Cpu,
  adapterDevices: Server,
  adapterPipelineLog: Workflow,
  integrationsHub: Plug,
  mlFeatureMonitor: Microscope,
} satisfies Record<NavManifestIconKey, FunctionalComponent>

export function resolveNavIcon(name?: string | null): FunctionalComponent {
  if (name && name in map) return map[name as NavManifestIconKey]
  return Link2
}
