'use strict';

const PROPOSAL_TTL_MS = 2 * 60 * 60 * 1000;

/**
 * Auto-mode skill: triages integration adapter health and may propose an internal incident (approval required).
 *
 * @param {object} params
 * @param {string} params.runId
 * @param {string} params.parkId
 * @param {string|null} params.parkName
 * @param {import('../runtime/tool-registry').ToolRegistry} params.toolRegistry
 * @param {(row: object) => Promise<import('../../../../models').AgentStep>} params.createStep
 * @param {(row: object) => Promise<import('../../../../models').AgentAction>} params.createAction
 */
async function runAdapterHealthTriage(params) {
  const { runId, parkId, parkName, toolRegistry, createStep, createAction } = params;
  const toolContext = { parkId, runId };
  let stepIndex = 0;
  const expiresAt = new Date(Date.now() + PROPOSAL_TTL_MS);

  await createStep({
    runId,
    stepIndex: stepIndex++,
    stepType: 'plan',
    title: 'Adapter health triage (auto)',
    detailJson: { skillId: 'adapter_health_triage', parkId, proposalsExpireAt: expiresAt.toISOString() },
  });

  const stepRow = await createStep({
    runId,
    stepIndex: stepIndex++,
    stepType: 'tool',
    title: 'Operations dashboard snapshot',
    detailJson: { toolName: 'read.dashboard_summary', args: {} },
  });

  let dashboard = {};
  try {
    dashboard = (await toolRegistry.execute('read.dashboard_summary', toolContext, {})) || {};
  } catch {
    dashboard = {};
  }

  await createAction({
    runId,
    stepId: stepRow.id,
    actionType: 'tool.invoke',
    status: 'completed',
    payloadJson: { toolName: 'read.dashboard_summary' },
    resultJson: { ok: true },
  });

  const count = Number(dashboard?.integrationFailures ?? dashboard?.openIncidents ?? 0) || 0;
  const markdown = [
    `# Adapter health — ${parkName || parkId}`,
    '',
    `Recent integration flow failures: **${count}**`,
    '',
    count > 5
      ? 'Consider reviewing adapter pipelines and opening a platform incident if errors persist.'
      : 'No elevated adapter failure rate detected in the latest window.',
    '',
    '_Generated by adapter_health_triage (template v1)._',
  ].join('\n');

  if (count > 5) {
    await createAction({
      runId,
      stepId: stepRow.id,
      actionType: 'incident.propose',
      status: 'pending',
      payloadJson: {
        title: 'Elevated adapter failure rate',
        severity: 'MEDIUM',
        summary: `${count} recent integration flow failures for park ${parkName || parkId}`,
      },
      expiresAt,
    });
  }

  return { markdown };
}

module.exports = { runAdapterHealthTriage };
