'use strict';

/**
 * Auto-mode skill: summarizes open incidents, recommendations, and forecasts for shift handover (read-only).
 *
 * @param {object} params
 * @param {string} params.runId
 * @param {string} params.parkId
 * @param {string|null} params.parkName
 * @param {import('../runtime/tool-registry').ToolRegistry} params.toolRegistry
 * @param {(row: object) => Promise<import('../../../../models').AgentStep>} params.createStep
 * @param {(row: object) => Promise<import('../../../../models').AgentAction>} params.createAction
 */
async function runShiftHandoverWriter(params) {
  const { runId, parkId, parkName, toolRegistry, createStep, createAction } = params;
  const toolContext = { parkId, runId };
  let stepIndex = 0;

  await createStep({
    runId,
    stepIndex: stepIndex++,
    stepType: 'plan',
    title: 'Shift handover summary (auto)',
    detailJson: { skillId: 'shift_handover_writer', parkId },
  });

  const toolPlan = [
    { name: 'read.incidents_list', title: 'Open incidents', args: { limit: 30, offset: 0 } },
    { name: 'read.forecast_summary', title: 'Forecast snapshot', args: { limit: 15 } },
    { name: 'read.dashboard_summary', title: 'Dashboard summary', args: {} },
  ];

  const toolOutputs = {};
  for (const spec of toolPlan) {
    const stepRow = await createStep({
      runId,
      stepIndex: stepIndex++,
      stepType: 'tool',
      title: spec.title,
      detailJson: { toolName: spec.name, args: spec.args },
    });
    const output = await toolRegistry.execute(spec.name, toolContext, spec.args);
    toolOutputs[spec.name] = output;
    await createAction({
      runId,
      stepId: stepRow.id,
      actionType: 'tool.invoke',
      status: 'completed',
      payloadJson: { toolName: spec.name },
      resultJson: { ok: true },
    });
  }

  const lines = [
    `# Shift handover — ${parkName || parkId}`,
    '',
    '## Incidents',
    JSON.stringify(toolOutputs['read.incidents_list'] ?? {}, null, 2).slice(0, 2000),
    '',
    '## Forecasts',
    JSON.stringify(toolOutputs['read.forecast_summary'] ?? {}, null, 2).slice(0, 1500),
    '',
    '_Generated by shift_handover_writer (template v1, read-only)._',
  ];

  return { markdown: lines.join('\n') };
}

module.exports = { runShiftHandoverWriter };
