module.exports = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_REFRESH: 'auth.refresh',
  ZONE_CREATE: 'zone.create',
  ZONE_UPDATE: 'zone.update',
  ZONE_DELETE: 'zone.delete',
  RIDE_CREATE: 'ride.create',
  RIDE_UPDATE: 'ride.update',
  RIDE_DELETE: 'ride.delete',
  RIDE_STATUS_CHANGE: 'ride.status_change',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DELETE: 'staff.delete',
  EVENT_CREATE: 'event.create',
  RECOMMENDATION_STATUS: 'recommendation.status_change',
  RECOMMENDATION_AI_SCORE: 'recommendation.ai_score',
  INCIDENT_CREATE: 'incident.create',
  INCIDENT_UPDATE: 'incident.update',
  INCIDENT_DELETE: 'incident.delete',
  PLATFORM_SETTING_UPDATE: 'platform_setting.update',
  UNS_SPY_DISCOVERY_APPROVE: 'uns_spy.discovery.approve',
  UNS_SPY_DISCOVERY_REJECT: 'uns_spy.discovery.reject',
  UNS_SPY_DISCOVERY_IGNORE: 'uns_spy.discovery.ignore',
  UNS_SPY_MQTT_PROPOSAL_APPROVE: 'uns_spy.mqtt_proposal.approve',
  UNS_SPY_MQTT_PROPOSAL_REJECT: 'uns_spy.mqtt_proposal.reject',
};
